---
- name: config_checks | Managing Sensu Checks
  sensu_check:
    name: "{{ item.name }}"
    command: "{{ item.command }}"
    interval: "{{ item.interval }}"
    subscribers: "{{ item.subscribers|join (',')}}"
    state: "{{ item.state }}"
  with_items: '{{ sensu_checks }}'
  notify:
    - restart sensu-api
    - restart sensu-server
